CLASS zcl_lab_40_actual_budget_3336 DEFINITION INHERITING FROM ZCL_LAB_39_BUDGET_3336
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_40_actual_budget_3336 IMPLEMENTATION.
ENDCLASS.
