CLASS zcl_lab_37_screen_3336 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA: screen_type TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_lab_37_screen_3336 IMPLEMENTATION.
ENDCLASS.
